{
 "title": "NetApp HCI - H615C Server Systems",
 "description": "Hardware Metrics for NetApp H-Series 615C (IPMI)",
 "tags": [
  "NetApp HCI",
  "Compute",
  "IPMI"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "platform", "label": "NetApp HCI System Series", "query": "netapp.hci.compute.*" },
   { "name": "hostname", "label": "NetApp HCI System System", "query": "netapp.hci.compute.h615.*" }
  ]
 },
 "panels": [
  {
   "title": "Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Board Temperature - $hostname",
   "type": "gauge",
   "description": "Different systems have different operating ranges and different data centers run at different temperatures. Feel free to examine the details of sensor that's measured and adjust Warning and Critical level for your environment. \n\nNote that Grafana alerts need to be separately configured.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_PCH_system_board__7_1_, 'System Board Temperature')"
    }
   ]
  },
  {
   "title": "CPU Temperature - $hostname",
   "type": "gauge",
   "description": "Different CPUs have different operating temperatures, so gauge thresholds should probably be customized for the CPU with lowest operating temperatures in your environment.\n\nExample: Intel Xeon Gold 6240Y - Max 74C, so we may want to see a warning at 55C and critical at 65C",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_CPU0_invalid__65_1_, 'CPU0')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_CPU1_invalid__65_1_, 'CPU1')"
    }
   ]
  },
  {
   "title": "System Board Voltage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(netapp.hci.compute.h615.$hostname.ipmi.voltage-Volt_P12V_system_board__7_1_, 3)"
    }
   ]
  },
  {
   "title": "Temperature Indicators - $hostname",
   "type": "graph",
   "description": "This panel serves to help you spot temperature trends in over days or weeks.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_Inlet_processor__3_0_, 'Inlet Processor')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_Outlet_system_board__7_1_, 'Outlet System Board')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_CPU0_invalid__65_1_, 'CPU0')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_CPU1_invalid__65_1_, 'CPU1')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_GPU1_system_board__7_0_, 'GPU1')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_GPU2_system_board__7_0_, 'GPU2')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_GPU3_system_board__7_0_, 'GPU3')"
    }
   ]
  },
  {
   "title": "Fan Speeds - $hostname",
   "type": "graph",
   "description": "Average fan speeds are expected to be consistent if system workload and environment temperature remain stable.\n\nIf BIOS settings that impact Power Consumption are changed, Fan Speeds are likely to change as well.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "target": "alias(consolidateBy(netapp.hci.compute.h615.$hostname.ipmi.fanspeed-Fan_SYS1_1_system_board__7_0_, 'average'), 'Avg Fan RPM')"
    }
   ]
  },
  {
   "title": "Chassis Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.*Fan_SYS0_0*, 'Fan1')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.*Fan_SYS1_0*, 'Fan2')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.*Fan_SYS2_0*, 'Fan3')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.*Fan_SYS3_0*, 'Fan4')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.*Fan_SYS4_0*, 'Fan5')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.*Fan_SYS5_0*, 'Fan6')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.*Fan_SYS6_0*, 'Fan7')"
    }
   ]
  },
  {
   "title": "Power Consumption - $hostname",
   "type": "gauge",
   "description": "Power Consumption does not have \"critical level\" per se, as PSU on the H615C are redundant so should one PSU fail, the other can consume \"twice as much\" power.\n\nHowever, users who care about energy consumption may want to examine system activity in the case it regularly consumes more power than expected.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "alias(netapp.hci.compute.h615.h615t4.ipmi.power-PSU0_Input_power_supply__10_1_, 'PSU1')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.h615t4.ipmi.power-PSU1_Input_power_supply__10_1_, 'PSU2')"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "description": "If you don't have a H615C-A4321 in your environment, you may delete this panel. \n\nMaximum NVIDIA Tesla T4 operating temperature is 86C. \n\nNote that Grafana alerts need to be separately configured.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_GPU1_system_board__7_0_, 'GPU0')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_GPU2_system_board__7_0_, 'GPU1')"
    },
    {
     "target": "alias(netapp.hci.compute.h615.$hostname.ipmi.temperature-Temp_GPU2_system_board__7_0_, 'GPU2')"
    }
   ]
  }
 ]
}