{
 "title": "NetApp HCI - SolidFire Volume Histograms",
 "tags": [
  "SolidFire",
  "NetApp HCI"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Element Cluster Name", "query": "netapp.solidfire.cluster.*" },
   {
    "name": "volumeID",
    "label": "Volume ID",
    "query": "netapp.solidfire.cluster.*.volumeID.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Histogram of Read Requests for Volume $volumeID",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of requests per Bucket" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(derivative(netapp.solidfire.cluster.$cluster.volumeID.$volumeID.readBlockSizes.*))"
    }
   ]
  },
  {
   "title": "Histogram of Write Requests for Volume $volumeID",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Number of requests per Bucket" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(derivative(netapp.solidfire.cluster.$cluster.volumeID.$volumeID.writeBlockSizes.*))"
    }
   ]
  },
  {
   "title": "Actual IOPS for Volume  $volumeID",
   "type": "graph",
   "description": "Actual IOPS may be useful for comparison vs. by-bucket IO request size breakdown obtained from QoS histograms",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "substr(netapp.solidfire.cluster.$cluster.volumeID.$volumeID.actualIOPS, 5, 6)"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "stat",
   "description": "How much the client is using the volume (0% - it's not, 120% - it's using Burst IOPS)",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 14 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "target": "netapp.solidfire.cluster.$cluster.volumeID.$volumeID.volumeUtilization",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Volume Heatmap (Time Spent Below Min IOPS) Volume $volumeID",
   "type": "heatmap",
   "description": "This charts loses meaning if QoS policies have been changed during observed period",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 21 },
   "targets": [
    {
     "target": "aliasByMetric(derivative(netapp.solidfire.cluster.$cluster.volumeID.$volumeID.belowMinIopsPercentages.*))"
    }
   ]
  },
  {
   "title": "Throttle",
   "type": "stat",
   "description": "How much time the system is throttling this volume (0% - no throttling)",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 21 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "target": "netapp.solidfire.cluster.$cluster.volumeID.$volumeID.throttle",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}