{
 "title": "NetApp HCI - SolidFire Volume TopN",
 "description": "TopN Solidfire volumes by Average IOPS",
 "tags": [
  "SolidFire",
  "NetApp HCI"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "netapp.solidfire.cluster.*" },
   { "name": "TopN", "query": "1,5,10,20" }
  ]
 },
 "panels": [
  { "title": "Volume Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top $TopN WriteOps/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(highestAverage(keepLastValue(netapp.solidfire.cluster.$Cluster.accountID.*.volume.*.writeOps, 5), $TopN)), 7)"
    }
   ]
  },
  {
   "title": "Top $TopN Read Ops/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(keepLastValue(highestAverage(netapp.solidfire.cluster.$Cluster.accountID.*.volume.*.readOps, $TopN), 5)), 7)"
    }
   ]
  },
  {
   "title": "Top $TopN Write Bytes/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(perSecond(keepLastValue(netapp.solidfire.cluster.$Cluster.accountID.*.volume.*.writeBytes, 5)), $TopN), 7)"
    }
   ]
  },
  {
   "title": "Top $TopN Read Bytes/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(keepLastValue(highestAverage(netapp.solidfire.cluster.$Cluster.accountID.*.volume.*.readBytes, $TopN), 5)), 7)"
    }
   ]
  },
  {
   "title": "Top $TopN Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(netapp.solidfire.cluster.$Cluster.accountID.*.volume.*.writeLatencyUSec, $TopN), 7)"
    }
   ]
  },
  {
   "title": "Top $TopN Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "aliasByNode(highestAverage(netapp.solidfire.cluster.$Cluster.accountID.*.volume.*.readLatencyUSec, $TopN), 7)"
    }
   ]
  }
 ]
}