{
 "title": "NetApp HCI - SolidFire Storage Optimization",
 "description": "Dashboard with storage optimization-focused panels",
 "tags": [
  "SolidFire",
  "NetApp HCI"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "clusterID", "label": "Cluster Name", "query": "netapp.solidfire.cluster.*" },
   {
    "name": "volumeID",
    "label": "Volume ID",
    "query": "netapp.solidfire.cluster.*.volumeID.*"
   },
   {
    "name": "accountID",
    "label": "Account ID (Name)",
    "query": "netapp.solidfire.cluster.$clusterID.accountID.*"
   },
   {
    "name": "accountIdNum",
    "label": "Account ID (Numeric)",
    "query": "netapp.solidfire.cluster.*.accountID.*"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Level Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Space Used & Maximum",
   "type": "graph",
   "description": "When maxUsedSpace is hit, cluster has no space to write new data.\n\nMost users don't wait until nonZeroBlocks get close to maxUsedSpace (especially if they desire to tolerate the loss of one node)",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(netapp.solidfire.cluster.$clusterID.maxUsedSpace)"
    },
    {
     "target": "aliasByMetric(netapp.solidfire.cluster.$clusterID.usedSpace)"
    }
   ]
  },
  {
   "title": "Metadata Space Used & Maximum",
   "type": "graph",
   "description": "maxUsedMetadata space is the maximum amount of space available for volume metadata. \n\nIf usedMetadata space is growing quickly, make sure users or automation aren't leaving behind unnecessary clones or snapshots",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(netapp.solidfire.cluster.$clusterID.maxUsedMetadataSpace)"
    },
    {
     "target": "aliasByMetric(netapp.solidfire.cluster.$clusterID.usedMetadataSpace)"
    }
   ]
  },
  {
   "title": "Data Space Utilization Trend",
   "type": "btplc-trend-box-panel",
   "description": "Data capacity utilization trend shows change (% delta) over selected time period and (below) the current utiilzation (% full)",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "targets": [
    {
     "target": "asPercent(#C, #A)",
     "targetFull": "asPercent(aliasByMetric(netapp.solidfire.cluster.$clusterID.usedSpace), aliasByMetric(netapp.solidfire.cluster.$clusterID.maxUsedSpace))"
    }
   ]
  },
  {
   "title": "Metadata Space Utilization Trend",
   "type": "btplc-trend-box-panel",
   "description": "Metadata capacity utilization trend shows change (% delta)  over selected time period and (below) the current utiilzation (% full)",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "percent",
   "targets": [
    {
     "target": "asPercent(#C, #A)",
     "targetFull": "asPercent(aliasByMetric(netapp.solidfire.cluster.$clusterID.usedMetadataSpace), aliasByMetric(netapp.solidfire.cluster.$clusterID.maxUsedMetadataSpace))"
    }
   ]
  },
  { "title": "Volume Level Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$clusterID Volume Sizes over TIme",
   "type": "graph",
   "description": "Volume sizes over time (Top 10). \n\nMinimum volume size on SolidFire is 1GiB.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "repeat": "clusterID",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "highestCurrent(aliasByNode(removeBelowValue(netapp.solidfire.cluster.$clusterID.volumeID.*.volumeSize, 1073741824), 5), 10)"
    }
   ]
  },
  {
   "title": "Volume IDs with Efficiency not Higher than 2X ",
   "type": "graph",
   "description": "These volumes may be candidates for efficiency improvements.\n\nThis panel uses new metric paths (HCICollector v0.7) based on Volume IDs and in order to map IDs to Names click on the SolidFire UI link in top right corner of this dashboard and look it up in the SolidFire Web UI.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Compr x Dedupe" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "target": "substr(removeAboveValue(netapp.solidfire.cluster.$clusterID.volumeID.*.volumeEfficiency, 2), 5, 6)",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Volume IDs with Burst IOPS Credit > 600K",
   "type": "graph",
   "description": "Candidates for lower Burst IO Setting.\n\nYou may want to adjust values and create several similar indicators.\n\nThis panel uses new metric paths (HCICollector v0.7) based on Volume IDs and in order to map IDs to Names click on the SolidFire UI link in top right corner of this dashboard and look it up in the SolidFire Web UI",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "substr(removeBelowValue(netapp.solidfire.cluster.$clusterID.volumeID.*.burstIOPSCredit, 600000), 5, 6)"
    }
   ]
  },
  { "title": "Account Level Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Account Data Efficiency for Account ID (Num): $accountIdNum",
   "type": "graph",
   "description": "Data Efficiency for Account ID (Numeric)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "substr(netapp.solidfire.cluster.$clusterID.accountID.$accountIdNum.accountEfficiency, 4, 6)"
    }
   ]
  },
  {
   "title": "Volume Sizes by Account ID (Name): $accountID",
   "type": "grafana-piechart-panel",
   "description": "Size of all volumes belonging to an account (selected in Name drop-down list at the top)\n\nThis includes thin-provisioned capacity (which is unused capacity) and does not consider data efficiencies",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 27 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(netapp.solidfire.cluster.$clusterID.accountID.$accountID.volume.*.volumeSize, 7)"
    }
   ]
  },
  {
   "title": "Volume Efficiency for Account ID (Num): $accountIdNum",
   "type": "singlestat",
   "description": "Efficiency of data stored on volumes owned by an account (selected from Account ID (Numeric) drop-down list at the top; this is an inconvenience of storing this data in a location different - see Release Notes for v0.7)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(netapp.solidfire.cluster.$clusterID.accountID.$accountIdNum.accountEfficiency, '$accountIdNum')"
    }
   ]
  }
 ]
}