{
 "title": "NetApp HCI - SolidFire Multi-Cluster NOC View",
 "tags": [
  "SolidFire",
  "NetApp HCI"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "netapp.solidfire.cluster.*" }
  ]
 },
 "panels": [
  {
   "title": "$Cluster cluster Utilization %",
   "type": "singlestat",
   "description": "Cluster utilization is expected to hit close to 100% at maximum rated performance (or above) while spikes in utilization may also happen during Garbage Collection and other system jobs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "Cluster",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.clusterUtilization"
    }
   ]
  },
  {
   "title": "$Cluster IOPS",
   "type": "graph",
   "description": "Cluster IOPS",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "repeat": "Cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.readOps), 5), 'Read IOPS')"
    },
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.writeOps), 5), 'Write IOPS')"
    },
    {
     "target": "alias(keepLastValue(perSecond(sumSeries(netapp.solidfire.cluster.$Cluster.{readOps,writeOps})), 5), 'Total IOPS')"
    }
   ]
  },
  {
   "title": "$Cluster Read/Write Bytes / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "repeat": "Cluster",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.readBytes), 5), 'Read Bytes/s')"
    },
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.writeBytes), 5), 'Write Bytes/s')"
    },
    {
     "target": "alias(keepLastValue(sumSeries(perSecond(netapp.solidfire.cluster.$Cluster.{readBytes,writeBytes})), 5), 'Total Bytes/s')"
    }
   ]
  },
  {
   "title": "$Cluster Drive Activeness Status",
   "type": "graph",
   "description": "All drives except those that have failed or are being added or removed should be Active. \n\nIf you see unexpected changes in the Active Drives curve, examine your cluster.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "repeat": "Cluster",
   "yaxes": [
    { "format": "short", "label": "Active or Failed Disks" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.drives.*.active, 5), 6)"
    },
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.drives.*.available, 5), 6)"
    },
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.drives.*.unknown, 5), 6)"
    },
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.drives.*.removing, 5), 6)"
    },
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.drives.*.failed, 5), 6)"
    }
   ]
  },
  {
   "title": "$Cluster Drive Wear Level",
   "type": "bargauge",
   "description": "Wear is expected to gradually grow (and Drive Life Remaining decline), but below 50% should be rare. \nIn the case of accelerated or sudden decline in Life Remaining (say, 1%/week), it may be a good idea to contact Support.\n\nClick on the SolidFire UI link to see individual drives sorted by Wear Remaining",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "repeat": "Cluster",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Wear Level",
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "When Alias Displayed",
     "target": "substr(netapp.solidfire.cluster.$Cluster.drives.*.lifeRemainingPercent, -3, -1)",
     "units": "percent",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}