{
 "title": "NetApp HCI - SolidFire Cluster",
 "description": "Metrics for Element cluster",
 "tags": [
  "SolidFire",
  "NetApp HCI"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster Name", "query": "netapp.solidfire.cluster.*" }
  ]
 },
 "panels": [
  { "title": "Element Cluster Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Warnings",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.fault.warning"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.fault.error"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.fault.critical"
    }
   ]
  },
  {
   "title": "Fault History",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(netapp.solidfire.cluster.$Cluster.fault.critical), 'Cluster Critical Faults')"
    },
    {
     "target": "alias(sumSeries(netapp.solidfire.cluster.$Cluster.fault.error), 'Cluster Errors')"
    },
    {
     "target": "alias(sumSeries(netapp.solidfire.cluster.$Cluster.fault.warning), 'Cluster Warnigs')"
    }
   ]
  },
  { "title": "Storage Efficiencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Compression Factor",
   "type": "singlestat",
   "description": "Changes in compression factor are not instantly obvservable. \n\nIt may take up to an hour for changes to reflect in values obtained from the cluster API.\n",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.compression_factor"
    }
   ]
  },
  {
   "title": "Deduplication Factor",
   "type": "singlestat",
   "description": "Changes in deduplication factor are not instantly obvservable. \n\nIt may take up to an hour for changes to reflect in values obtained from the cluster API.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.dedupe_factor"
    }
   ]
  },
  {
   "title": "Efficiency Factor",
   "type": "singlestat",
   "description": "Efficiency factor shown here is product of Compression and Deduplication. \n\nIt can easily be modified to also consider Thin Provisioning.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.efficiency_cxd_factor"
    }
   ]
  },
  {
   "title": "Thin Provisioning Factor",
   "type": "singlestat",
   "description": "Ratio of all (zero and non-zero) blocks vs. non-zero blocks.\n\nIt may take up to an hour for changes to reflect in values obtained from the cluster API.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.thin_factor"
    }
   ]
  },
  { "title": "Cluster Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$Cluster IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.readOps), 5), 'Read IOPS')"
    },
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.writeOps), 5), 'Write IOPS')"
    },
    {
     "target": "alias(keepLastValue(perSecond(sumSeries(netapp.solidfire.cluster.$Cluster.{readOps,writeOps})), 5), 'Total IOPS')"
    }
   ]
  },
  {
   "title": "$Cluster Read/Write Bytes / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.readBytes), 5), 'Read Bytes/s')"
    },
    {
     "target": "alias(keepLastValue(perSecond(netapp.solidfire.cluster.$Cluster.writeBytes), 5), 'Write Bytes/s')"
    },
    {
     "target": "alias(keepLastValue(sumSeries(perSecond(netapp.solidfire.cluster.$Cluster.{readBytes,writeBytes})), 5), 'Total Bytes/s')"
    }
   ]
  },
  {
   "title": "$Cluster Cluster Recent I/O Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(netapp.solidfire.cluster.$Cluster.clusterRecentIOSize, 5), 'I/O Size')"
    }
   ]
  },
  { "title": "Cluster Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$Cluster Current Cluster Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "netapp.solidfire.cluster.$Cluster.clusterUtilization"
    }
   ]
  },
  {
   "title": "$Cluster Utilization Over Time",
   "type": "graph",
   "description": "CPU utilization of all SolidFire nodes in the selected cluster over time",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(keepLastValue(netapp.solidfire.cluster.$Cluster.clusterUtilizationScaled, 5), 100), 3)"
    }
   ]
  },
  {
   "title": "$Cluster Node CPU Usage per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.node.*.cpu, 5), 5)"
    }
   ]
  },
  {
   "title": "$Cluster Active iSCSI Sessions",
   "type": "graph",
   "description": "Active iSCSI sessions may be up to several hundred per storage node (see Element documentation) and depending on other factors (multipathing, number of clients connecting to each volume) it can be 2X or more of the number of active volumes.\n\nClusters with lots of volumes (Kubernetes, for example) may need to pay attention to this number.\n\nWhen the number of sessions goes up and down by the same number, there may be iSCSI clients out there trying to connect to non-existing targets.\n\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.activeSessions, 5), 3)"
    }
   ]
  },
  {
   "title": "$Cluster Drive Count",
   "type": "graph",
   "description": "It is expected to see one Block (used for volume metadata) and several Data (used for client data) disks per each SolidFire storage node.\n\nUnexpected changes should be examined.\n\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.drives.*.volume, 5), 6)"
    },
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.drives.*.block, 5), 6)"
    }
   ]
  },
  {
   "title": "$Cluster  Client Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(netapp.solidfire.cluster.$Cluster.clientQueueDepth, 5), 3)"
    }
   ]
  }
 ]
}