{
 "title": "SFC example  dashboard",
 "tags": [
  "solidfire",
  "sfc",
  "netapp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cluster faults",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "warning",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster_faults",
     "query": "SELECT mean(\"warning\") FROM \"cluster_faults\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "warning" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "error",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster_faults",
     "query": "SELECT mean(\"warning\") FROM \"cluster_faults\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "error" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "critical",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster_faults",
     "query": "SELECT mean(\"warning\") FROM \"cluster_faults\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "critical" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "best practices",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cluster_faults",
     "query": "SELECT mean(\"warning\") FROM \"cluster_faults\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bestPractices" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster capacity - recent IO size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "recent IO size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_capacity",
     "query": "SELECT mean(\"active_sessions\") FROM \"cluster_capacity\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cluster_recent_io_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster - normalized IOPS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "normalized IOPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cluster_performance",
     "select": [
      [
       { "params": [ "normalized_iops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes - CPU utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "CPU utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_performance",
     "query": "SELECT mean(\"cpu\") FROM \"node_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Node - network utilization",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "network utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node_performance",
     "select": [
      [
       { "params": [ "network_utilization_cluster" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "network_utilization_storage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Account storage efficiency",
   "type": "stat",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "account_efficiency",
     "query": "SELECT mean(\"storage_efficiency\") FROM \"volume_efficiency\" WHERE $timeFilter GROUP BY time($__interval), \"id\"::tag fill(null)",
     "select": [
      [
       { "params": [ "storage_efficiency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Account ID-to-Name mapping",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "accounts",
     "select": [
      [
       { "params": [ "volume_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume efficiency factor",
   "type": "stat",
   "description": "Compression x Deduplication",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id::tag" ], "type": "tag" }
     ],
     "measurement": "volume_efficiency",
     "query": "SELECT mean(\"storage_efficiency\") FROM \"volume_efficiency\" WHERE $timeFilter GROUP BY time($__interval), \"id\"::tag fill(null)",
     "select": [
      [
       { "params": [ "storage_efficiency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "iSCSI connections - time since last SCSI command",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "iscsi_sessions",
     "select": [
      [
       { "params": [ "ms_since_last_scsi_command" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tenants - volume count per tenant",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "accounts",
     "select": [
      [
       { "params": [ "volume_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume QoS histograms - write block sizes",
   "type": "timeseries",
   "description": "Red color represents idling below MinIOPS. Green means very little idling below MinIOPS. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "id::tag" ], "type": "tag" }
     ],
     "measurement": "histogram_write_block_sizes",
     "select": [
      [
       { "params": [ "b_000512_to_004095" ], "type": "field" }
      ],
      [
       { "params": [ "b_004096_to_008191" ], "type": "field" }
      ],
      [
       { "params": [ "b_008192_to_016383" ], "type": "field" }
      ],
      [
       { "params": [ "b_016384_to_032767" ], "type": "field" }
      ],
      [
       { "params": [ "b_032768_to_65535" ], "type": "field" }
      ],
      [
       { "params": [ "b_065536_to_131071" ], "type": "field" }
      ],
      [
       { "params": [ "b_131072_plus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=", "value": "data" }
     ]
    }
   ]
  },
  {
   "title": "Volume QoS histograms - read block sizes",
   "type": "timeseries",
   "description": "Red color represents idling below MinIOPS. Green means very little idling below MinIOPS. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "id::tag" ], "type": "tag" }
     ],
     "measurement": "histogram_read_block_sizes",
     "select": [
      [
       { "params": [ "b_000512_to_004095" ], "type": "field" }
      ],
      [
       { "params": [ "b_004096_to_008191" ], "type": "field" }
      ],
      [
       { "params": [ "b_008192_to_016383" ], "type": "field" }
      ],
      [
       { "params": [ "b_016384_to_032767" ], "type": "field" }
      ],
      [
       { "params": [ "b_032768_to_65535" ], "type": "field" }
      ],
      [
       { "params": [ "b_065536_to_131071" ], "type": "field" }
      ],
      [
       { "params": [ "b_131072_plus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=", "value": "data" }
     ]
    }
   ]
  },
  {
   "title": "Volume QoS Histogram - % time below MinIOPS",
   "type": "heatmap",
   "description": "Ideally, most bars should appear in the bottom half of this chart, indicating that the volume is spending less than 50% of time *not* using more than MinIOPS value.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "histogram_below_min_iops_percentages",
     "select": [
      [
       { "params": [ "b_01_to_19" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "alias" ], "type": "alias" }
      ],
      [
       { "params": [ "b_20_to_39" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "alias" ], "type": "alias" }
      ],
      [
       { "params": [ "b_40_to_59" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "alias" ], "type": "alias" }
      ],
      [
       { "params": [ "b_60_to_79" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "alias" ], "type": "alias" }
      ],
      [
       { "params": [ "b_80_to_100" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=", "value": "data" }
     ]
    }
   ]
  },
  {
   "title": "Volume performance - actual IOPS",
   "type": "stat",
   "description": "Shows actual IOPS on volumes by ID or by name (pick one in GROUP BY)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "volume_performance",
     "query": "SELECT mean(\"average_io_size\"), mean(\"actual_iops\") FROM \"volume_performance\" WHERE (\"id\"::tag = '134') AND $timeFilter GROUP BY time($__interval), \"name\"::tag fill(null)",
     "select": [
      [
       { "params": [ "actual_iops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume performance - actual IOPS",
   "type": "timeseries",
   "description": "Shows actual IOPS on volumes by ID or by name (pick one in GROUP BY)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "volume_performance",
     "query": "SELECT mean(\"average_io_size\"), mean(\"actual_iops\") FROM \"volume_performance\" WHERE (\"id\"::tag = '134') AND $timeFilter GROUP BY time($__interval), \"name\"::tag fill(null)",
     "select": [
      [
       { "params": [ "actual_iops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume performance - zero blocks as % of volume size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/($A+$B)", "type": "math" }
   ]
  },
  {
   "title": "Volumes - QoS ID on volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "volumes",
     "select": [
      [
       { "params": [ "qos_policy_id" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume performance - Burst IO credit in 4kB Ops",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "volume_performance",
     "select": [
      [
       { "params": [ "burst_io_credit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume properties - async replication delay",
   "type": "timeseries",
   "description": "Chart shows (if you have paired volumes with outgoing replication) delay in seconds for Async replication. \n-1 means the volume is not paired, 0 - no delay, > 0 is delay in seconds. \nChart only shows values > -1, i.e. any non-out-replicating  volumes are hidden.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "volume_performance",
     "select": [
      [
       { "params": [ "async_delay" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "async_delay::field", "operator": ">", "value": "-1" }
     ]
    }
   ]
  },
  {
   "title": "Volume properties - replication mode",
   "type": "stat",
   "description": "Chart shows (if you have paired volumes with outgoing replication) one of the modes - Async, Sync, SnapshotsOnly",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" }
     ],
     "measurement": "volumes",
     "select": [
      [
       { "params": [ "remote_replication_mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster::tag", "operator": "=", "value": "PROD" }
     ]
    }
   ]
  },
  {
   "title": "Volume sync jobs (DR site) - remaining time (s) on volume ID",
   "type": "timeseries",
   "description": "NOTE: pick the remote cluster to get this information. Start another instance of SFC for the other cluster and in query select WHERE cluster::tag is the remote cluster's name.\nThere are several kinds of sync jobs in SolidFire and SFC v2.0.0 only remote sync job type is implemented. Submit your ListSyncJobs JSON output example to SFC issues to have other jobs added.\nhttps://docs.netapp.com/us-en/element-software/api/reference_element_api_listsyncjobs.html",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "dst_volume_id::tag" ], "type": "tag" }
     ],
     "measurement": "sync_jobs",
     "select": [
      [
       { "params": [ "remaining_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "cluster::tag", "operator": "=", "value": "DR" }
     ]
    }
   ]
  },
  {
   "title": "SFC internal metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "function::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sfc_metrics",
     "select": [
      [
       { "params": [ "time_taken" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}